# Generated by Django 5.2.6 on 2025-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('solar_output', models.FloatField()),
                ('battery_level', models.FloatField()),
                ('diesel_usage', models.FloatField()),
            ],
        ),
    ]
